# Generated by Django 4.2.3 on 2023-09-19 04:58

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(unique=True)),
                ('created_by_user', models.CharField(unique=True)),
                ('tag_id', models.CharField(unique=True)),
                ('filename', models.CharField(unique=True)),
                ('text', models.CharField()),
                ('description', models.CharField()),
                ('uploadTime', models.DateTimeField()),
                ('privacy', models.BooleanField()),
            ],
            managers=[
                ('objects', data.models.AudioDataManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('OTHER', 'Other')], default='OTHER')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')])),
            ],
        ),
    ]
