# Generated by Django 4.2.3 on 2023-11-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdata',
            name='file',
        ),
    ]
