# Generated by Django 4.2.3 on 2023-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_created_by_user_audiodata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='tag_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='task_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
