# Generated by Django 4.2.3 on 2023-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_audiodata_description_alter_audiodata_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='tag_id',
            field=models.CharField(max_length=255),
        ),
    ]
