# Generated by Django 4.2.3 on 2023-09-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_taskdata_taskmetadata_delete_audiodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmetadata',
            old_name='uploadTime',
            new_name='upload_time',
        ),
    ]
