# Generated by Django 4.2.3 on 2023-09-22 17:16

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_uploadtime_taskmetadata_upload_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taskdata',
            managers=[
                ('objects', data.models.TaskManager()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')]),
        ),
        migrations.AlterField(
            model_name='taskmetadata',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskmetadata',
            name='tag_id',
            field=models.IntegerField(),
        ),
    ]
